on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: kcreg1.azurecr.io
        username: ${{ secrets.acr_kcreg1_username }}
        password: ${{ secrets.acr_kcreg1_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/." -f  "dockerFile" -t kcreg1.azurecr.io/kcaks01:${{ github.sha }}
        docker push kcreg1.azurecr.io/kcaks01:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_kcaks01_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep kcaks013965 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace kcaks013965`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: kcaks013965
        container-registry-url: kcreg1.azurecr.io
        container-registry-username: ${{ secrets.acr_kcreg1_username }}
        container-registry-password: ${{ secrets.acr_kcreg1_password }}
        secret-name: kcaks01dockerauth
       
    - uses: azure/k8s-deploy@v1
      with:
        namespace: kcaks013965
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          kcreg1.azurecr.io/kcaks01:${{ github.sha }}
        imagepullsecrets: |
          kcaks01dockerauth